-- @Autor:  Ariadna Lázaro
-- @Fecha:  15/10/2023
-- @Descripcion:DDL de la base 1

-- 
-- TABLE: ARTICULO_2 
--

CREATE TABLE F_AALM_ARTICULO_2(
    ARTICULO_ID    NUMBER(10, 0)     NOT NULL,
    TITULO         VARCHAR2(40)      NOT NULL,
    RESUMEN         VARCHAR2(500)     NOT NULL,
    TEXTO          VARCHAR2(4000)    NOT NULL,
    CONSTRAINT F_AALM_ARTICULO_2_PK PRIMARY KEY (ARTICULO_ID)
)
;


-- 
-- TABLE: REVISTA_1 
--

CREATE TABLE F_AALM_REVISTA_1(
    REVISTA_ID              NUMBER(10, 0)    NOT NULL,
    FOLIO                   VARCHAR2(10)     NOT NULL,
    TITULO                  VARCHAR2(40)     NOT NULL,
    FECHA_PUBLICACION       DATE             NOT NULL,
    REVISTA_ADICIONAL_ID    NUMBER(10, 0),
    CONSTRAINT F_AALM_REVISTA_1_PK PRIMARY KEY (REVISTA_ID)
)
;



-- 
-- TABLE: ARTICULO_REVISTA_1 
--

CREATE TABLE F_AALM_ARTICULO_REVISTA_1(
    ARTICULO_REVISTA_ID    NUMBER(10, 0)    NOT NULL,
    FECHA_APROBACION       DATE             NOT NULL,
    CALIFICACION           NUMBER(3, 1)     NOT NULL,
    REVISTA_ID             NUMBER(10, 0)    NOT NULL,
    ARTICULO_ID            NUMBER(10, 0)    NOT NULL,
    CONSTRAINT F_AALM_ARTICULO_REVISTA_1_PK
    PRIMARY KEY (ARTICULO_REVISTA_ID),
    CONSTRAINT F_AALM_ARTICULO_REVISTA_1_ARTICULO_ID_FK 
    FOREIGN KEY (ARTICULO_ID)  REFERENCES F_AALM_ARTICULO_2(ARTICULO_ID),
    CONSTRAINT F_AALM_ARTICULO_REVISTA_1_F_AALM_REVISTA_ID_FK
    FOREIGN KEY (REVISTA_ID) REFERENCES F_AALM_REVISTA_1(REVISTA_ID)
)
;


-- 
-- TABLE: PAIS_1 
--

CREATE TABLE F_AALM_PAIS_1(
    PAIS_ID             NUMBER(3, 0)    NOT NULL,
    CLAVE               VARCHAR2(3)     NOT NULL,
    NOMBRE              VARCHAR2(40)    NOT NULL,
    REGION_ECONOMICA    VARCHAR2(1)     NOT NULL,
    CONSTRAINT F_AALM_PAIS_1_PK PRIMARY KEY (PAIS_ID)
)
;

-- 
-- TABLE: SUSCRIPTOR_2 
--

CREATE TABLE F_AALM_SUSCRIPTOR_2(
    SUSCRIPTOR_ID        NUMBER(10, 0)    NOT NULL,
    NOMBRE               VARCHAR2(40)     NOT NULL,
    AP_PATERNO           VARCHAR2(40)     NOT NULL,
    AP_MATERNO           VARCHAR2(40)     NOT NULL,
    FECHA_INSCRIPCION    DATE             NOT NULL,
    PAIS_ID              NUMBER(3, 0)     NOT NULL,
    CONSTRAINT F_AALM_SUSCRIPTOR_2_PK PRIMARY KEY (SUSCRIPTOR_ID),
    CONSTRAINT F_AALM_SUSCRIPTOR_2_PAIS_ID_FK 
    FOREIGN KEY(PAIS_ID) REFERENCES F_AALM_PAIS_1(PAIS_ID)
)
;



-- 
-- TABLE: SUSCRIPTOR_1 
--

CREATE TABLE F_AALM_SUSCRIPTOR_1(
    SUSCRIPTOR_ID    NUMBER(10, 0)    NOT NULL,
    NUM_TARJETA      VARCHAR2(16)     NOT NULL,
    CONSTRAINT F_AALM_SUSCRIPTOR_1_PK 
    PRIMARY KEY (SUSCRIPTOR_ID)
)
;



-- 
-- TABLE: PAGO_1 
--

CREATE TABLE F_AALM_PAGO_SUSCRIPTOR_1(
    NUM_PAGO         NUMBER(10, 0)    NOT NULL,
    SUSCRIPTOR_ID    NUMBER(10, 0)    NOT NULL,
    FECHA_PAGO       DATE             NOT NULL,
    IMPORTE          NUMBER(8, 2)     NOT NULL,
    RECIBO_PAGO      BLOB             NOT NULL,
    CONSTRAINT F_AALM_PAGO_SUSCRIPTOR_1_PK 
    PRIMARY KEY (NUM_PAGO, SUSCRIPTOR_ID),
    CONSTRAINT F_AALM_PAGO_SUSCRIPTOR_1_SUSCRIPTOR_ID_FK 
    FOREIGN KEY(SUSCRIPTOR_ID) REFERENCES F_AALM_SUSCRIPTOR_1(SUSCRIPTOR_ID)
)
;



-- 
-- TABLE: SUSCRIPTOR_3 
--

CREATE TABLE F_AALM_SUSCRIPTOR_3(
    SUSCRIPTOR_ID        NUMBER(10, 0)    NOT NULL,
    NOMBRE               VARCHAR2(40)     NOT NULL,
    AP_PATERNO           VARCHAR2(40)     NOT NULL,
    AP_MATERNO           VARCHAR2(40)     NOT NULL,
    FECHA_INSCRIPCION    DATE             NOT NULL,
    PAIS_ID              NUMBER(3, 0)     NOT NULL,
    CONSTRAINT F_AALM_SUSCRIPTOR_3_PK PRIMARY KEY (SUSCRIPTOR_ID)
)
;


