-- @Autor:  Ariadna Lázaro
-- @Fecha:  15/10/2023
-- @Descripcion:DDL de la base 2

-- 
-- TABLE: ARTICULO_1
--

CREATE TABLE F_AALM_ARTICULO_1(
    ARTICULO_ID    NUMBER(10, 0)    NOT NULL,
    PDF            BLOB             NOT NULL,
    CONSTRAINT F_AALM_ARTICULO_1_PK PRIMARY KEY (ARTICULO_ID)
)
;


-- 
-- TABLE: REVISTA_2 
--

CREATE TABLE F_AALM_REVISTA_2(
    REVISTA_ID              NUMBER(10, 0)    NOT NULL,
    FOLIO                   VARCHAR2(10)     NOT NULL,
    TITULO                  VARCHAR2(40)     NOT NULL,
    FECHA_PUBLICACION       DATE             NOT NULL,
    REVISTA_ADICIONAL_ID    NUMBER(10, 0),
    CONSTRAINT F_AALM_REVISTA_2_PK PRIMARY KEY (REVISTA_ID)
)
;


-- 
-- TABLE: ARTICULO_REVISTA_2 
--

CREATE TABLE F_AALM_ARTICULO_REVISTA_2(
    ARTICULO_REVISTA_ID    NUMBER(10, 0)    NOT NULL,
    FECHA_APROBACION       DATE             NOT NULL,
    CALIFICACION           NUMBER(3, 1)     NOT NULL,
    REVISTA_ID             NUMBER(10, 0)    NOT NULL,
    ARTICULO_ID            NUMBER(10, 0)    NOT NULL,
    CONSTRAINT F_AALM_ARTICULO_REVISTA_2_PK 
    PRIMARY KEY (REVISTA_ID),
    CONSTRAINT F_AALM_ARTICULO_REVISTA_2_REVISTA_ID_FK 
    FOREIGN KEY(REVISTA_ID) REFERENCES F_AALM_REVISTA_2(REVISTA_ID),
    CONSTRAINT F_AALM_ARTICULO_REVISTA_2_ARTICULO_ID_FK 
    FOREIGN KEY(ARTICULO_ID) REFERENCES F_AALM_ARTICULO_1(ARTICULO_ID)
)
;



-- 
-- TABLE: PAGO_2 
--

CREATE TABLE F_AALM_PAGO_SUSCRIPTOR_2(
    NUM_PAGO         NUMBER(10, 0)    NOT NULL,
    SUSCRIPTOR_ID    NUMBER(10, 0)    NOT NULL,
    FECHA_PAGO       DATE             NOT NULL,
    IMPORTE          NUMBER(8, 2)     NOT NULL,
    RECIBO_PAGO      BLOB             NOT NULL,
    CONSTRAINT F_AALM_PAGO_SUSCRIPTOR_2_PK 
    PRIMARY KEY (NUM_PAGO, SUSCRIPTOR_ID)
)
;




-- 
-- TABLE: PAIS_2 
--

CREATE TABLE F_AALM_PAIS_2(
    PAIS_ID             NUMBER(3, 0)    NOT NULL,
    CLAVE               VARCHAR2(3)     NOT NULL,
    NOMBRE              VARCHAR2(40)    NOT NULL,
    REGION_ECONOMICA    VARCHAR2(1)     NOT NULL,
    CONSTRAINT F_AALM_PAIS_2_PK PRIMARY KEY (PAIS_ID)
)
;



-- 
-- TABLE: SUSCRIPTOR_4 
--

CREATE TABLE F_AALM_SUSCRIPTOR_4(
    SUSCRIPTOR_ID        NUMBER(10, 0)    NOT NULL,
    NOMBRE               VARCHAR2(40)     NOT NULL,
    AP_PATERNO           VARCHAR2(40)     NOT NULL,
    AP_MATERNO           VARCHAR2(40)     NOT NULL,
    FECHA_INSCRIPCION    DATE             NOT NULL,
    PAIS_ID              NUMBER(3, 0)     NOT NULL,
    CONSTRAINT F_AALM_SUSCRIPTOR_4_PK PRIMARY KEY (SUSCRIPTOR_ID),
    CONSTRAINT F_AALM_SUSCRIPTOR_4_PAIS_ID_FK 
    FOREIGN KEY(PAIS_ID) REFERENCES F_AALM_PAIS_2(PAIS_ID)
)
;
